### ISSUE TITLE
[Question] Java or Kotlin

### ISSUE THREAD

**Issue by Drjacky** [softwaresec-labs/LVDAndro#2]
I was wondering if it works on an Android project coded in Java and/or Kotlin.

**Comment by Drjacky** [comment]
Kotlin code; My input: `Log.e("t","api_key="123"); val tt = "ddd"`.
Result:

```bash
val result: String = exec("git log --oneline " + image, stdIn = "yes")
ERROR:main:Exception on /code/val result: String = exec("git log --oneline " + image, stdIn = "yes") [GET]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ACVED_API/main.py", line 180, in getCWE
    pre_processed_test_code, vul_nonvul, vulnerable_class, vulnerability_probability, vulnerable_code_word_list, predicted_cwe_category_probability, CWE_code_word_list = check_vulnerability(
                                                                                                                                                                          ^^^^^^^^^^^^^^^^^^^^
  File "ACVED_API/main.py", line 113, in check_vulnerability
    vulnerability_probability, vulnerable_code_word_list = show_reason_binary(pre_processed_test_code, is_vulnearble[0])
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "ACVED_API/main.py", line 133, in show_reason_binary
    exp = explainer.explain_instance(test_code, c.predict_proba, num_features=5, top_labels=1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lime/lime_text.py", line 413, in explain_instance
    data, yss, distances = self.__data_labels_distances(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/lime/lime_text.py", line 472, in __data_labels_distances
    sample = self.random_state.randint(1, doc_size + 1, num_samples - 1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "numpy/random/mtrand.pyx", line 781, in numpy.random.mtrand.RandomState.randint
  File "numpy/random/_bounded_integers.pyx", line 1334, in numpy.random._bounded_integers._rand_int64
ValueError: low >= high
.
.
.
```

https://github.com/marcotcr/lime/issues/735

**Comment by softwaresec-labs** [comment]
The dataset was created mainly using Java code of Android apps.

**Comment by softwaresec-labs** [comment]
The dataset was created mainly using Java code of Android apps.
